<a href="https://colab.research.google.com/github/gitmor/colabtutorials/blob/main/ColabAndnumpyDemo0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ('hello, world')

hello, world


# What does above code do?
- The above code takes a string as argument and prints the string passed as argument
- In above example, string "hello world" is passed to pyhton function  print 

In [3]:
def HelloWorldXY(x, y):
  if (x < 10):
    print("Hello World, x was < 10")
  elif (x < 20):
    print("Hello World, x was >= 10 but < 20")
  else:
    print("Hello World, x was >= 20")
  return x + y

for i in range(8, 356, 5):  # i=8, 13, 18, 23 (start, stop, step)
  print("--- Now running with i: {}".format(i))
  r = HelloWorldXY(i,i)
  print("Result from HelloWorld: {}".format(r))


--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 16
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 26
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 36
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 46
--- Now running with i: 28
Hello World, x was >= 20
Result from HelloWorld: 56
--- Now running with i: 33
Hello World, x was >= 20
Result from HelloWorld: 66
--- Now running with i: 38
Hello World, x was >= 20
Result from HelloWorld: 76
--- Now running with i: 43
Hello World, x was >= 20
Result from HelloWorld: 86
--- Now running with i: 48
Hello World, x was >= 20
Result from HelloWorld: 96
--- Now running with i: 53
Hello World, x was >= 20
Result from HelloWorld: 106
--- Now running with i: 58
Hello World, x was >= 20
Result from HelloWorld: 116
--- Now running with i: 63
Hello World, x was >= 20
Result from HelloWorld: 126
--- Now running with i: 68
Hello 

## Introduction
This project is done by VIvek & I will explain a few features below"

In [ ]:
print(HelloWorldXY(1,2))

Hello World, x was < 10
3


In [ ]:
import numpy as np  # Make numpy available using np.

# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [ ]:
import numpy as np  # Make numpy available using np.

# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [ ]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [ ]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>


In [ ]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.35272254 0.28295575 0.0683586 ]
 [0.71598289 0.91028171 0.02130261]
 [0.6678673  0.47779348 0.58997831]]


In [ ]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


In [ ]:
# Python Program illustarting 
# working of argmax() 
  
import numpy as geek  
  
# Working on 2D array 
array =  geek.random.randint(16, size=(4, 4)) 
print("INPUT ARRAY : \n", array) 
  
# No axis mentioned, so works on entire array 
print("\nIndex of Max element : ", geek.argmax(array)) 
  
# returning Indices of the max element 
# as per the indices 
  
'''    
   [[ 0  3  8 13] 
    [12 11  2 11] 
    [ 5 13  8  3] 
    [12 15  3  4]] 
      ^  ^  ^  ^ 
     12 15  8  13  - element 
     1  3   0  0   - indices 
'''
print("\nIndices of Max element by COLUMN (axis 0)): ", geek.argmax(array, axis = 0)) 
  
  
'''    
                            ELEMENT   INDEX 
   ->[[ 0  3  8 13]           13        3 
    ->[12 11  2 11]           12        0 
    ->[ 5 13  8  3]           13        1 
    ->[12 15  3  4]]          15        1 
        
'''
print("\nIndices of Max element by ROW (axis 1)): ", geek.argmax(array, axis = 1)) 

INPUT ARRAY : 
 [[ 4  6  4  7]
 [12  8  2  8]
 [14 11 11  7]
 [13 10  3 11]]

Index of Max element :  8

Indices of Max element by COLUMN (axis 0)):  [2 2 2 3]

Indices of Max element by ROW (axis 1)):  [3 0 0 0]
